### ISSUE TITLE
[Roadmap?] [ToDo List?] Do these exist?

### ISSUE THREAD

**Issue by jeffward01** [rainxh11/Revoke.NET#2]
Hello!

I think this is a **GREAT** project, I see so many posts online about how to invalidate JWT tokens, and everyone seems to be a bit clueless.  
I very much appreciate this library and would love to contribute.

Do you have a 'to-do' list, or 'roadmap' so that I can start making some pull requests?

Thanks!

**Comment by rainxh11** [comment]
This library is a general way to revoke based on whatever criteria not just JWT
I don't have a 'to-do' list, you can make pull request and contribute

**Comment by jeffward01** [comment]
Sounds good, thank you!
