### ISSUE TITLE
[Question] Can you please explain briefly what the class MemoryCacheBlackList does?

### ISSUE THREAD

**Issue by jeffward01** [rainxh11/Revoke.NET#4]
Hello!

Quick question, can you briefly explain the differences between `MemoryBlackList` and `MemoryCacheBlackList`?

I have my assumptions about them, but would love for you to elaborate, I need a little clarity on the purpose of `MemoryCacheBlackList` and why there is a separate class from `MemoryBlackList` 

Thanks

**Comment by rainxh11** [comment]
MemoryBlackList is using ConcurrentDictionary to store data
MemoryCacheBlackList is using Microsoft IMemoryCache instead

**Comment by jeffward01** [comment]
> MemoryBlackList is using ConcurrentDictionary to store data MemoryCacheBlackList is using Microsoft IMemoryCache instead

Sounds good, this is very helpful. I will add this in the XML comments and get this added. I appreciate this.

Thanks for the invite by the way 😄  I still want to keep you involved and updated on all features and actions I commit / push / build.

--

Big thank you for the **very** fast action on GitHub. you are awesome
